### ISSUE TITLE
V2 - Feedbacks

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#254]
- [ ] **DatePicker** https://github.com/InseeFr/Lunatic/issues/140
- [ ] [Simpson ](https://inseefr.github.io/Lunatic/storybook-v2/?path=/story/behavior-simpsons--missing) - question 20 : "Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bvalue%2C%20type%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings." **Maybe it is a table ?**
- [ ] https://github.com/InseeFr/Lunatic/issues/205 : but **controls are wip I think ?**
- [x] No more **tooltips** ?
- [ ] #303 : "Nous allons vous interroger sur if (isnull(NBHAB)) then "le statut d'occupation de votre ménage" else (if (cast(NBHAB,integer)=1) then "votre statut d'occupation" else (if (not(isnull(nbpersmaj)) and cast(nbpersmaj,integer)>1) then "le statut d'occupation de votre ménage, les statuts d'occupation individuels des occupants du logement" else "le statut d'occupation de votre ménage" ) ) et la date d’installation dans le logement."
- [x] **Refused / Don't know on an InputNumber** => does it record 0 instead of null ?
