### ISSUE TITLE
Finalize restoring Estanpette developments on RosterForLoop

### ISSUE THREAD

**Issue by BulotF** [InseeFr/Lunatic#852]
Estanpette developments are stored on the branch mvp-eap : https://github.com/InseeFr/Lunatic/compare/2.7...feat/mvp-eap

The main commit dealing with rosterForLoop is this one : https://github.com/InseeFr/Lunatic/commit/a8d50e2721adc129aa5ee02f5e804188f3c8af59

This commit included : 

components:
- [x] replacing headers with header #843  
- [x] mutualize header with table's one
- [x] using the label for the question instead of the add button #846 
- [ ]  homogenizing question structure with other components by using LunaticComponentWithLabel
- [x]  Memoization on Table Row #853 

type: 
- [x]  remove type "headers"

CSS: 
- [x] #857

storybook: 
- [x] add source-with-header.json to stories
- [ ] update in source-with-header.json, header/label to replace the string with {value, type}
- [ ]  update label to have a question label that doesn't look like a addButton label

other: 
- [ ] src/hooks/use-did-change.ts : function useDidChange was created to test which keys changed. I don't know if it remains useful

**Comment by ddecrulle** [comment]
I just edited issue to track all development that as been done.

For memoization purpose keep in mind this comment https://github.com/InseeFr/Lunatic/pull/853#issuecomment-1898388450.
